-- Create a table for links
create table links (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  url text not null,
  title text,
  description text,
  category text,
  status text default 'active' check (status in ('active', 'archive', 'trash')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table links enable row level security;

-- Create policies
create policy "Users can view their own links" on links
  for select using (auth.uid() = user_id);

create policy "Users can insert their own links" on links
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own links" on links
  for update using (auth.uid() = user_id);

create policy "Users can delete their own links" on links
  for delete using (auth.uid() = user_id);
